name: markdown_viewer
description: A Markdown renderer for Flutter. Render Markdown String to rich
  text output.
version: 0.6.2
repository: https://github.com/tagnote-app/markdown_viewer
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  dart_markdown:
    git: https://github.com/kumsumit/dart_markdown.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
